### ISSUE TITLE
Discrepancy between hex.pm and github releases

### ISSUE THREAD

**Issue by pdgonzalez872** [primait/ex_fuzzywuzzy#4]
Hi! Thanks for the library!

I'm trying to look at the code for v0.2.0 and have not been able to find it in the releases (https://github.com/primait/ex_fuzzywuzzy/releases) here. Could you please push the updates here as well? Looks like the latest is 0.1.0 and in hex.pm you the 0.2.0 is available (https://hex.pm/packages/ex_fuzzywuzzy/0.2.0).

Thanks!

**Comment by pdgonzalez872** [comment]
I'm not sure if this is currently maintained followed, so I'm going to ping the last commiter to the repo @mbusi. If you are all following already, sorry! And thanks again!

**Comment by Johnabell** [comment]
Thank you for getting in touch, you are indeed correct that there is no Github release associated with version 0.2.0. However, the code is available against the tag: https://github.com/primait/ex_fuzzywuzzy/tree/0.2.0/lib. I hope that helps. I intend to ensure that for the next release (which hopefully should be in the next couple of days) we will ensure that there is a corresponding Github release.

**Comment by pdgonzalez872** [comment]
Excellent! Thanks!

**Comment by Johnabell** [comment]
The new release has been made. Thank you for getting in touch, I think we can now mark this as resolved.
