### ISSUE TITLE
Can´t apply ratio

### ISSUE THREAD

**Issue by sonic182** [primait/ex_fuzzywuzzy#9]
![image](https://github.com/primait/ex_fuzzywuzzy/assets/4070466/e0521229-c8dd-43d7-a4f0-c90bf51b37ab)

I'm getting this error

I'm using

```
erlang 26.1.2
elixir 1.16.1-otp-26
```

A bit weird

**Comment by csuriano23** [comment]
You need to configure the similarity engine, specifying the similarity function (Levehnstein and Jaro Winkler available out-of-the-box), the case sensitivity flag and the precision of the result. You can do that specifying the options at runtime like:

```
iex(1)> ExFuzzywuzzy.ratio("foo", "oof", [similarity_fn: &ExFuzzywuzzy.Similarity.Levenshtein.calculate/2, case_sensitive: false, precision: 0])
67.0
```
or using a config.exs in your app ([reference](https://github.com/primait/ex_fuzzywuzzy/blob/master/config/config.exs#L5) inside the repo)

**Comment by sonic182** [comment]
You could add an example doc for livebook case
